const developers = [
  {
    username: "naruto_uzumaki",
    age: 19,
    email: "naruto@konoha.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Naruto",
    phoneNo: "9000000001",
    gender: "Male",
    designation: "Frontend Developer",
  },
  {
    username: "sasuke_uchiha",
    age: 19,
    email: "sasuke@konoha.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Sasuke",
    phoneNo: "9000000002",
    gender: "Male",
    designation: "Backend Developer",
  },
  {
    username: "sakura_haruno",
    age: 19,
    email: "sakura@konoha.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Sakura",
    phoneNo: "9000000003",
    gender: "Female",
    designation: "UI/UX Designer",
  },
  {
    username: "itachi_uchiha",
    age: 21,
    email: "itachi@akatsuki.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Itachi",
    phoneNo: "9000000004",
    gender: "Male",
    designation: "DevOps Engineer",
  },
  {
    username: "kakashi_hatake",
    age: 27,
    email: "kakashi@konoha.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Kakashi",
    phoneNo: "9000000005",
    gender: "Male",
    designation: "Full Stack Developer",
  },
  {
    username: "luffy_d_monkey",
    age: 19,
    email: "luffy@onepiece.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Luffy",
    phoneNo: "9000000006",
    gender: "Male",
    designation: "Frontend Developer",
  },
  {
    username: "zoro_roronoa",
    age: 21,
    email: "zoro@onepiece.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Zoro",
    phoneNo: "9000000007",
    gender: "Male",
    designation: "Backend Developer",
  },
  {
    username: "nami_swann",
    age: 20,
    email: "nami@onepiece.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Nami",
    phoneNo: "9000000008",
    gender: "Female",
    designation: "Product Manager",
  },
  {
    username: "sanji_vinsmoke",
    age: 21,
    email: "sanji@onepiece.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Sanji",
    phoneNo: "9000000009",
    gender: "Male",
    designation: "UI Developer",
  },
  {
    username: "levi_ackerman",
    age: 25,
    email: "levi@aot.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Levi",
    phoneNo: "9000000010",
    gender: "Male",
    designation: "Security Engineer",
  },
  {
    username: "eren_yeager",
    age: 19,
    email: "eren@aot.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Eren",
    phoneNo: "9000000011",
    gender: "Male",
    designation: "Software Engineer",
  },
  {
    username: "mikasa_ackerman",
    age: 19,
    email: "mikasa@aot.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Mikasa",
    phoneNo: "9000000012",
    gender: "Female",
    designation: "Backend Developer",
  },
  {
    username: "gojo_satoru",
    age: 28,
    email: "gojo@jujutsu.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Gojo",
    phoneNo: "9000000013",
    gender: "Male",
    designation: "Tech Lead",
  },
  {
    username: "itadori_yuji",
    age: 18,
    email: "yuji@jujutsu.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Yuji",
    phoneNo: "9000000014",
    gender: "Male",
    designation: "Frontend Developer",
  },
  {
    username: "megumi_fushiguro",
    age: 18,
    email: "megumi@jujutsu.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Megumi",
    phoneNo: "9000000015",
    gender: "Male",
    designation: "Backend Developer",
  },
  {
    username: "tanjiro_kamado",
    age: 17,
    email: "tanjiro@demonslayer.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Tanjiro",
    phoneNo: "9000000016",
    gender: "Male",
    designation: "Full Stack Developer",
  },
  {
    username: "nezuko_kamado",
    age: 16,
    email: "nezuko@demonslayer.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Nezuko",
    phoneNo: "9000000017",
    gender: "Female",
    designation: "UI Designer",
  },
  {
    username: "zenitsu_agatsuma",
    age: 17,
    email: "zenitsu@demonslayer.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Zenitsu",
    phoneNo: "9000000018",
    gender: "Male",
    designation: "QA Engineer",
  },
  {
    username: "inosuke_hashibira",
    age: 17,
    email: "inosuke@demonslayer.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Inosuke",
    phoneNo: "9000000019",
    gender: "Male",
    designation: "DevOps Engineer",
  },
  {
    username: "light_yagami",
    age: 20,
    email: "light@deathnote.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Light",
    phoneNo: "9000000020",
    gender: "Male",
    designation: "AI Engineer",
  },
  {
    username: "l_lawliet",
    age: 21,
    email: "l@deathnote.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=L",
    phoneNo: "9000000021",
    gender: "Male",
    designation: "Cyber Security Analyst",
  },
  {
    username: "goku_son",
    age: 30,
    email: "goku@dragonball.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Goku",
    phoneNo: "9000000022",
    gender: "Male",
    designation: "Software Architect",
  },
  {
    username: "vegeta_prince",
    age: 32,
    email: "vegeta@dragonball.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Vegeta",
    phoneNo: "9000000023",
    gender: "Male",
    designation: "Backend Engineer",
  },
  {
    username: "bulma_brief",
    age: 29,
    email: "bulma@dragonball.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Bulma",
    phoneNo: "9000000024",
    gender: "Female",
    designation: "Data Scientist",
  },
  {
    username: "ichigo_kurosaki",
    age: 18,
    email: "ichigo@bleach.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Ichigo",
    phoneNo: "9000000025",
    gender: "Male",
    designation: "Full Stack Developer",
  },
  {
    username: "rukia_kuchiki",
    age: 18,
    email: "rukia@bleach.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Rukia",
    phoneNo: "9000000026",
    gender: "Female",
    designation: "Frontend Developer",
  },
  {
    username: "killua_zoldyck",
    age: 14,
    email: "killua@hxh.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Killua",
    phoneNo: "9000000027",
    gender: "Male",
    designation: "Backend Developer",
  },
  {
    username: "gon_freecss",
    age: 14,
    email: "gon@hxh.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Gon",
    phoneNo: "9000000028",
    gender: "Male",
    designation: "Frontend Developer",
  },
  {
    username: "hisoka_moro",
    age: 28,
    email: "hisoka@hxh.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Hisoka",
    phoneNo: "9000000029",
    gender: "Male",
    designation: "Cloud Engineer",
  },
  {
    username: "asta_magic",
    age: 17,
    email: "asta@blackclover.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Asta",
    phoneNo: "9000000030",
    gender: "Male",
    designation: "Software Developer",
  },
  {
    username: "yuno_grinberryall",
    age: 17,
    email: "yuno@blackclover.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Yuno",
    phoneNo: "9000000031",
    gender: "Male",
    designation: "Backend Developer",
  },
  {
    username: "rem_rezero",
    age: 18,
    email: "rem@rezero.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Rem",
    phoneNo: "9000000032",
    gender: "Female",
    designation: "UI Designer",
  },
  {
    username: "emilia_rezero",
    age: 19,
    email: "emilia@rezero.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Emilia",
    phoneNo: "9000000033",
    gender: "Female",
    designation: "Frontend Developer",
  },
  {
    username: "alucard_vampire",
    age: 30,
    email: "alucard@hellsing.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Alucard",
    phoneNo: "9000000034",
    gender: "Male",
    designation: "Security Engineer",
  },
  {
    username: "kaneki_ken",
    age: 20,
    email: "kaneki@tokyoghoul.com",
    profileImg: "https://api.dicebear.com/7.x/adventurer/svg?seed=Kaneki",
    phoneNo: "9000000035",
    gender: "Male",
    designation: "Backend Developer",
  },
];

// ===========================================================================

const developers2 = [
  {
    username: "arjun_dev",
    age: 24,
    email: "arjun.dev@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/men/1.jpg",
    phoneNo: "9876543201",
    gender: "Male",
    designation: "Frontend Developer",
  },
  {
    username: "priya_codes",
    age: 26,
    email: "priya.codes@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/women/2.jpg",
    phoneNo: "9876543202",
    gender: "Female",
    designation: "Backend Developer",
  },
  {
    username: "rohit_js",
    age: 25,
    email: "rohit.js@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/men/3.jpg",
    phoneNo: "9876543203",
    gender: "Male",
    designation: "Full Stack Developer",
  },
  {
    username: "sneha_ui",
    age: 23,
    email: "sneha.ui@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/women/4.jpg",
    phoneNo: "9876543204",
    gender: "Female",
    designation: "UI Developer",
  },
  {
    username: "vishal_java",
    age: 27,
    email: "vishal.java@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/men/5.jpg",
    phoneNo: "9876543205",
    gender: "Male",
    designation: "Java Developer",
  },
  {
    username: "ananya_react",
    age: 24,
    email: "ananya.react@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/women/6.jpg",
    phoneNo: "9876543206",
    gender: "Female",
    designation: "React Developer",
  },
  {
    username: "karthik_node",
    age: 28,
    email: "karthik.node@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/men/7.jpg",
    phoneNo: "9876543207",
    gender: "Male",
    designation: "Node.js Developer",
  },
  {
    username: "megha_api",
    age: 26,
    email: "megha.api@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/women/8.jpg",
    phoneNo: "9876543208",
    gender: "Female",
    designation: "API Developer",
  },
  {
    username: "sandeep_sql",
    age: 29,
    email: "sandeep.sql@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/men/9.jpg",
    phoneNo: "9876543209",
    gender: "Male",
    designation: "Database Developer",
  },
  {
    username: "pooja_web",
    age: 22,
    email: "pooja.web@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/women/10.jpg",
    phoneNo: "9876543210",
    gender: "Female",
    designation: "Web Developer",
  },
  {
    username: "manoj_cloud",
    age: 30,
    email: "manoj.cloud@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/men/11.jpg",
    phoneNo: "9876543211",
    gender: "Male",
    designation: "Cloud Engineer",
  },
  {
    username: "kavya_uiux",
    age: 25,
    email: "kavya.uiux@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/women/12.jpg",
    phoneNo: "9876543212",
    gender: "Female",
    designation: "UI/UX Developer",
  },
  {
    username: "ajay_php",
    age: 28,
    email: "ajay.php@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/men/13.jpg",
    phoneNo: "9876543213",
    gender: "Male",
    designation: "PHP Developer",
  },
  {
    username: "neha_test",
    age: 27,
    email: "neha.test@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/women/14.jpg",
    phoneNo: "9876543214",
    gender: "Female",
    designation: "QA Engineer",
  },
  {
    username: "rahul_mobile",
    age: 26,
    email: "rahul.mobile@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/men/15.jpg",
    phoneNo: "9876543215",
    gender: "Male",
    designation: "Mobile App Developer",
  },
  {
    username: "isha_flutter",
    age: 24,
    email: "isha.flutter@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/women/16.jpg",
    phoneNo: "9876543216",
    gender: "Female",
    designation: "Flutter Developer",
  },
  {
    username: "deepak_python",
    age: 29,
    email: "deepak.python@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/men/17.jpg",
    phoneNo: "9876543217",
    gender: "Male",
    designation: "Python Developer",
  },
  {
    username: "richa_ml",
    age: 28,
    email: "richa.ml@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/women/18.jpg",
    phoneNo: "9876543218",
    gender: "Female",
    designation: "ML Engineer",
  },
  {
    username: "nitin_devops",
    age: 31,
    email: "nitin.devops@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/men/19.jpg",
    phoneNo: "9876543219",
    gender: "Male",
    designation: "DevOps Engineer",
  },
  {
    username: "shruti_angular",
    age: 25,
    email: "shruti.angular@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/women/20.jpg",
    phoneNo: "9876543220",
    gender: "Female",
    designation: "Angular Developer",
  },
  // ---- continuing till 35 ----
  {
    username: "amit_go",
    age: 32,
    email: "amit.go@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/men/21.jpg",
    phoneNo: "9876543221",
    gender: "Male",
    designation: "Golang Developer",
  },
  {
    username: "sonal_data",
    age: 27,
    email: "sonal.data@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/women/22.jpg",
    phoneNo: "9876543222",
    gender: "Female",
    designation: "Data Engineer",
  },
  {
    username: "harish_ios",
    age: 29,
    email: "harish.ios@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/men/23.jpg",
    phoneNo: "9876543223",
    gender: "Male",
    designation: "iOS Developer",
  },
  {
    username: "divya_android",
    age: 26,
    email: "divya.android@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/women/24.jpg",
    phoneNo: "9876543224",
    gender: "Female",
    designation: "Android Developer",
  },
  {
    username: "tarun_csharp",
    age: 30,
    email: "tarun.csharp@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/men/25.jpg",
    phoneNo: "9876543225",
    gender: "Male",
    designation: "C# Developer",
  },
  {
    username: "monika_bi",
    age: 28,
    email: "monika.bi@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/women/26.jpg",
    phoneNo: "9876543226",
    gender: "Female",
    designation: "BI Developer",
  },
  {
    username: "yash_block",
    age: 27,
    email: "yash.block@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/men/27.jpg",
    phoneNo: "9876543227",
    gender: "Male",
    designation: "Blockchain Developer",
  },
  {
    username: "nisha_ai",
    age: 25,
    email: "nisha.ai@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/women/28.jpg",
    phoneNo: "9876543228",
    gender: "Female",
    designation: "AI Engineer",
  },
  {
    username: "lokesh_sys",
    age: 33,
    email: "lokesh.sys@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/men/29.jpg",
    phoneNo: "9876543229",
    gender: "Male",
    designation: "System Engineer",
  },
  {
    username: "payal_support",
    age: 24,
    email: "payal.support@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/women/30.jpg",
    phoneNo: "9876543230",
    gender: "Female",
    designation: "Support Engineer",
  },
  {
    username: "sunil_lead",
    age: 35,
    email: "sunil.lead@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/men/31.jpg",
    phoneNo: "9876543231",
    gender: "Male",
    designation: "Tech Lead",
  },
  {
    username: "aarti_pm",
    age: 34,
    email: "aarti.pm@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/women/32.jpg",
    phoneNo: "9876543232",
    gender: "Female",
    designation: "Product Manager",
  },
  {
    username: "rakesh_arch",
    age: 38,
    email: "rakesh.arch@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/men/33.jpg",
    phoneNo: "9876543233",
    gender: "Male",
    designation: "Software Architect",
  },
  {
    username: "simran_hrtech",
    age: 29,
    email: "simran.hrtech@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/women/34.jpg",
    phoneNo: "9876543234",
    gender: "Female",
    designation: "HR Tech Analyst",
  },
  {
    username: "omkar_intern",
    age: 21,
    email: "omkar.intern@gmail.com",
    profileImg: "https://randomuser.me/api/portraits/men/35.jpg",
    phoneNo: "9876543235",
    gender: "Male",
    designation: "Software Intern",
  },
];
